on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Deploy code to Lambda
      uses: coneypylon/action-lambda-python-zip@master
      with:
        platform: 'manylinux2014_x86_64'
        lambda_layer_arn: ${{ secrets.LAMBDA_LAYER_ARN }}
        lambda_function_name: ${{ secrets.LAMBDA_FUNCTION_NAME }}
        lambda_region: 'ca-central-1'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Curl for Github Actions
      uses: sozo-design/curl@v1.0.2
      with:
        args: "https://6eybfhhyye.execute-api.ca-central-1.amazonaws.com/default/cnr-eprs-runner --header 'Content-Type: application/json' --header 'x-api-key: ${{ secrets.TESTING_KEY }}' --data '{ \"query\":\"QZTORMTL0606410002\"}'"